# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 02:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delicacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Delicacy', max_length=80)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='/default_delicacy.jpg', upload_to='delicacies')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Delicacy_Seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DelicacyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('flash_status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_type', models.IntegerField(default=1)),
                ('delicacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Delicacy', to='jollof.Delicacy')),
                ('delicacy_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DelicacyBuyer', to=settings.AUTH_USER_MODEL)),
                ('delicacy_flash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DelicacyFlash', to=settings.AUTH_USER_MODEL)),
                ('delicacy_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DelicacySeller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FutureLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=128)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fbid'],
            },
        ),
        migrations.CreateModel(
            name='Jollof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(default='/default_jollof.jpg', upload_to='jollofs')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JollofOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('flash_status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_type', models.IntegerField(default=1)),
                ('jollof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Jollof', to='jollof.Jollof')),
                ('jollof_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jollof_Buyer', to=settings.AUTH_USER_MODEL)),
                ('jollof_flash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jollof_Flash', to=settings.AUTH_USER_MODEL)),
                ('jollof_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jollof_Seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=128, unique=True)),
                ('gender', models.IntegerField(default=1)),
                ('phone_number', models.CharField(max_length=128)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current_state', models.CharField(default='DEFAULT', max_length=128)),
                ('location_history', models.TextField(default='')),
                ('available', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('s', 'Seller'), ('b', 'Buyer'), ('f', 'Flash')], default='s', max_length=20)),
                ('has_order', models.BooleanField(default=False)),
                ('code', models.CharField(default='', max_length=6, unique=True)),
                ('restaurant', models.CharField(default='', max_length=128)),
                ('opening_hour', models.IntegerField(default=0)),
                ('closing_hour', models.IntegerField(default=1)),
                ('start_day', models.IntegerField(default=1)),
                ('end_day', models.IntegerField(default=7)),
                ('delivers', models.BooleanField(default=False)),
                ('delivery_price', models.FloatField(default=0.0)),
                ('average_delivery_time', models.IntegerField(default=0)),
                ('logo', models.ImageField(default='/default_logo.png', upload_to='logos')),
                ('star', models.IntegerField(default=1)),
                ('flash_code', models.CharField(default='', max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.ImageField(default='/no-img.jpg', upload_to='samples')),
            ],
        ),
    ]
