# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jollofcode',
            name='seller',
        ),
        migrations.DeleteModel(
            name='JollofCode',
        ),
    ]
