# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='current_state',
            field=models.CharField(default='DEFAULT', max_length=128),
        ),
        migrations.AddField(
            model_name='seller',
            name='current_state',
            field=models.CharField(default='DEFAULT', max_length=128),
        ),
    ]
