# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0002_auto_20171204_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delicacy',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Delicacy_Seller', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='delicacyorder',
            name='delicacy_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DelicacyBuyer', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='delicacyorder',
            name='delicacy_flash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DelicacyFlash', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='delicacyorder',
            name='delicacy_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DelicacySeller', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='jollof',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='jolloforder',
            name='jollof_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jollof_Buyer', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='jolloforder',
            name='jollof_flash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jollof_Flash', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='jolloforder',
            name='jollof_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jollof_Seller', to='jollof.Profile'),
        ),
    ]
