# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0002_auto_20170523_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jollof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='company',
        ),
        migrations.AddField(
            model_name='seller',
            name='restaurant',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jollof',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.Seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='jollof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jollof.Jollof'),
        ),
    ]
