# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0002_auto_20170614_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicacy',
            name='name',
            field=models.CharField(default='Delicacy', max_length=80),
        ),
    ]
