# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0003_auto_20170525_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='JollofCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.Seller')),
            ],
        ),
    ]
