# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0003_auto_20171206_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('n', 'New User'), ('o', 'Old User')], default='n', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.Profile')),
            ],
            options={
                'ordering': ['referral'],
            },
        ),
    ]
