# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0003_delicacy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='average_delivery_time',
            field=models.IntegerField(default=0),
        ),
    ]
