# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0004_seller_average_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
