# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0004_jollofcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
