# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0005_seller_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='delivery_price',
            field=models.FloatField(default=0.0),
        ),
    ]
