# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0006_flashconversation_sellerconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelicacyFlashConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='DelicacySellerConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='JollofFlashConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='JollofSellerConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='buyerconversation',
            name='mid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='flashconversation',
            name='mid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sellerconversation',
            name='mid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='jollofsellerconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.SellerConversation'),
        ),
        migrations.AddField(
            model_name='jollofsellerconversation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.JollofOrder'),
        ),
        migrations.AddField(
            model_name='jollofflashconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.FlashConversation'),
        ),
        migrations.AddField(
            model_name='jollofflashconversation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.JollofOrder'),
        ),
        migrations.AddField(
            model_name='delicacysellerconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.SellerConversation'),
        ),
        migrations.AddField(
            model_name='delicacysellerconversation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.DelicacyOrder'),
        ),
        migrations.AddField(
            model_name='delicacyflashconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.FlashConversation'),
        ),
        migrations.AddField(
            model_name='delicacyflashconversation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.DelicacyOrder'),
        ),
    ]
