# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0006_seller_delivery_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='delicacy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='delicacyorder',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='jollof',
            options={'ordering': ['description']},
        ),
        migrations.AlterModelOptions(
            name='jolloforder',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['restaurant'], 'verbose_name': 'seller', 'verbose_name_plural': 'sellers'},
        ),
    ]
