# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0006_auto_20170526_0556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='JollofOrder',
        ),
    ]
