# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0007_auto_20170529_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delicacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='DelicacyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delicacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.Delicacy')),
                ('delicacy_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.Buyer')),
                ('delicacy_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof.Seller')),
            ],
        ),
    ]
