# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0007_auto_20170624_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
