# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0007_auto_20171208_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delicacyorder',
            name='delicacy_flash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DelicacyFlash', to='jollof.Profile'),
        ),
        migrations.AlterField(
            model_name='jolloforder',
            name='jollof_flash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jollof_Flash', to='jollof.Profile'),
        ),
    ]
