# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0008_delicacy_delicacyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='closing_hour',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seller',
            name='end_day',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='seller',
            name='opening_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='start_day',
            field=models.IntegerField(default=1),
        ),
    ]
