# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0008_seller_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(default='/no-img.jpg', upload_to='samples')),
            ],
        ),
    ]
