# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0009_auto_20171216_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_withdraw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='flash_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='flash_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='month_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='vendor_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
