# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0009_auto_20170530_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='has_order',
            field=models.BooleanField(default=False),
        ),
    ]
