# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0009_samplefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefile',
            name='file',
            field=models.ImageField(default='/no-img.jpg', upload_to='samples'),
        ),
    ]
