# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0010_auto_20170704_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicacy',
            name='image',
            field=models.ImageField(default='/default_delicacy.jpg', upload_to='delicacies'),
        ),
        migrations.AddField(
            model_name='jollof',
            name='image',
            field=models.ImageField(default='/default_jollof.jpg', upload_to='jollofs'),
        ),
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(default='/default_logo.jpg', upload_to='logos'),
        ),
    ]
