# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0010_buyer_has_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='delivers',
            field=models.BooleanField(default=False),
        ),
    ]
