# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0011_seller_delivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicacyorder',
            name='order_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jolloforder',
            name='order_type',
            field=models.IntegerField(default=1),
        ),
    ]
