# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0013_futurelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='star',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(default='/default_logo.png', upload_to='logos'),
        ),
    ]
