# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0014_auto_20170723_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='history',
            new_name='location_history',
        ),
    ]
