# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0015_auto_20170916_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=128, unique=True)),
                ('flash_code', models.CharField(default='', max_length=9)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.IntegerField(default=1)),
                ('phone_number', models.CharField(default='0', max_length=128)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current_state', models.CharField(default='DEFAULT', max_length=128)),
                ('location_history', models.TextField(default='')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='delicacyorder',
            name='flash_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jolloforder',
            name='flash_status',
            field=models.IntegerField(default=0),
        ),
    ]
