# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0016_auto_20171027_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicacyorder',
            name='flash_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flash',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flash',
            name='flash_code',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='jolloforder',
            name='flash_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delicacyorder',
            name='delicacy_flash',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof.Flash'),
        ),
        migrations.AlterField(
            model_name='flash',
            name='phone_number',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='jolloforder',
            name='jollof_flash',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof.Flash'),
        ),
    ]
