# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollof', '0016_auto_20171113_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicacyorder',
            name='delicacy_flash',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof.Flash'),
        ),
        migrations.AddField(
            model_name='jolloforder',
            name='jollof_flash',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof.Flash'),
        ),
    ]
